### ISSUE TITLE
Integration tests hang after completed

### ISSUE THREAD

**Issue by justin1121** [OpenMined/Grid#147]
The integration tests hang after being completed. This is caused by the client launching a thread that never shuts down. It could be caused by this thread: https://github.com/OpenMined/Grid/blob/master/grid/clients/base.py#L46 but there may be others.

**Comment by lhhong** [comment]
I have narrowed the cause to this line: https://github.com/OpenMined/Grid/blob/master/grid/workers/base_worker.py#L164
The generator will hold onto the thread preventing exit. I could think of 2 solutions exit the loop, one is to use multiprocess instead of threads (I am new to the code base and not sure of the implications). The other is to publish a "terminate" message to gracefully exit the loop.
