### ISSUE TITLE
Get models out of grid and back to jupyter notebook.

### ISSUE THREAD

**Issue by bendecoste** [OpenMined/Grid#50]
The grid will train models in tree mode, and will publish models to IPFS, but there is not currently any good way for a data scientist to pull models back out from the grid and use them.

One idea might look like this

```python
c = Client()
models = c.get_best_models_for('mnist')

# models is a list of keras.Sequential (or w/e the best architecture was
models.predict(input)
```

Please share your ideas on a good flow for this.

**Comment by jvmancuso** [comment]
I think `Client.fit` should return everything you need.  I think we want it to return a message of type `transact` with the address of the best model at `model_addr`, so then all you'd need to do is call `best_model, _ = Client.receive_model(model_addr)` to receive the model you want, and then you'd use it like any other Keras model.

We should also eventually have a log of all the different models from training, so that if the user prefers a different model from the training process, they can extract the IPFS address from a log and call `receive_model` on it, e.g. if they suspect it to perform better for some reason.
